services:
  - type: web
    name: neodash
    env: static
    repo: https://github.com/sowsalim01/neodash.git
    rootDir: .
    buildCommand: chmod +x build-render.sh && ./build-render.sh
    staticPublishPath: dist
    routes:
      - route: /(.*)
        path: /index.html
