services:
  # Static Site
  - type: web
    name: neodash
    env: static
    buildCommand: "yarn install --frozen-lockfile=false && yarn build"
    staticPublishPath: dist
    routes:
      - route: /(.*)
        path: /index.html
    envVars:
      - key: NODE_ENV
        value: production
